import { chromium } from "@playwright/test";
const out = process.env.SHOTS_DIR || "/tmp/hq-shots"; import("node:fs").then(fs => fs.mkdirSync(out, { recursive: true }));
const browser = await chromium.launch({ executablePath: process.env.PW_CHROMIUM || undefined });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
page.on("pageerror", (e) => errors.push("PAGEERROR " + e.message));
await page.goto("http://localhost:3000/login", { waitUntil: "networkidle" });
await page.screenshot({ path: `${out}/01-login.png` });
await page.fill('input[name=email]', "pg@spectrumrobotics.ai");
await page.fill('input[name=password]', "SpectrumHQ-2026!");
await page.click('button[type=submit]:has-text("Sign in")');
await page.waitForURL(/\/hq/, { timeout: 20000 });
await page.waitForLoadState("networkidle");
await page.screenshot({ path: `${out}/02-my-day.png`, fullPage: true });
// dismiss tour if present
const done = page.locator(".driver-popover-close-btn");
if (await done.count()) await done.first().click();
await page.keyboard.press("Control+k");
await page.waitForTimeout(400);
await page.keyboard.type("hollywood");
await page.waitForTimeout(900);
await page.screenshot({ path: `${out}/03-palette.png` });
await page.keyboard.press("Escape");
const pr = await page.goto("http://localhost:3000/portal", { waitUntil: "load", timeout: 20000 }); console.log("portal status", pr && pr.status(), page.url());
await page.screenshot({ path: `${out}/04-portal-staff.png`, fullPage: true });
await page.goto("http://localhost:3000/signup", { waitUntil: "networkidle" });
await page.screenshot({ path: `${out}/05-signup.png` });
console.log("URL after login:", page.url());
console.log("console errors:", errors.length ? errors : "none");
await browser.close();
